@startuml
class Etudiant{
    NumeroEtudiant
    Nom
    Prenom
    DateDeNaissance
}
class Cours{
    Titre
    Codedumodule
}
class Examen{
    DatePotentiel
    coefficient
}
class Professeur{
    Nom
    Prenom
}
Etudiant "1..*" -- "0..*" Cours
Cours "1" -- Examen
Professeur "1" -right- "1..*" Cours
Etudiant "1..*" -- "0..*" Examen
(Etudiant, Examen) . Note

@enduml